server:
  port: 8080

spring:
  application:
    name: gateway-server

  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: payment
          uri: lb://payment-service
          predicates:
            - Path=/payment/**
        - id: email
          uri: lb://email-service
          predicates:
            - Path=/email/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
