server:
  port: 8084

spring:
  application:
    name: email-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

camunda:
  client:
    zeebe:
      grpc-address: "http://zeebe:26500"
      security:
        plaintext: true
